media:
  input: images/blog
  output: /images/blog

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: content/posts
    filename: "{slug}.md"
    format: yaml-frontmatter

    view:
      primary: title
      sort: date
      order: desc

    fields:
      - name: title
        label: Blog Title
        type: string
        required: true

      - name: slug
        label: URL Slug
        type: string
        required: true

      - name: date
        label: Publish Date
        type: date
        required: true

      - name: image
        label: Featured Image
        type: image
        required: false

      - name: category
        label: Category
        type: string
        required: true

      - name: metaTitle
        label: Meta Title
        type: string
        required: true

      - name: metaDescription
        label: Meta Description
        type: text
        required: true

      - name: body
        label: Blog Content
        type: rich-text
